[package]
name = "librespot"
version = "0.1.0-phts-np-01.0"
authors = ["Paul Liétar <paul@lietar.net>"]
license = "MIT"
description = "Open Source Spotify client library"
keywords = ["spotify"]
repository = "https://github.com/plietar/librespot"
readme = "README.md"
edition = "2018"

[package.metadata.deb]
maintainer = "librespot-org"
copyright = "2018 Paul Liétar"
license_file = ["LICENSE", "4"]
depends = "$auto"
extended_description = """\
librespot is an open source client library for Spotify. It enables applications \
to use Spotify's service, without using the official but closed-source \
libspotify. Additionally, it will provide extra features which are not \
available in the official library."""
section = "sound"
priority = "optional"
assets = [
    ["target/release/librespot", "usr/bin/", "755"],
    ["contrib/librespot.service", "lib/systemd/system/", "644"]
]

[workspace]

[lib]
name = "librespot"
path = "src/lib.rs"

# [[bin]]
# name = "librespot"
# path = "src/main.rs"
# doc = false
#
# [dependencies]
# base64 = "0.5.0"
# env_logger = "0.5.10"
# futures = "0.1.23"
# getopts = "0.2.14"
# hyper = "0.11.2"
# log = "0.4.0"
# num-bigint = "0.1.35"
# protobuf = "~2.0.5"
# rand = "0.3.13"
# rpassword = "0.3.0"
# serde = "1.0"
# serde_derive = "1.0"
# serde_json = "1.0"
# tokio-core = "0.1.2"
# tokio-io = "0.1"
# tokio-signal = "0.1.2"
# url = "1.7.0"
# sha-1 = "0.8.0"
# hex = "0.3.2"

[dependencies.librespot-audio]
path = "audio"
[dependencies.librespot-connect]
path = "connect"
[dependencies.librespot-core]
path = "core"
[dependencies.librespot-metadata]
path = "metadata"
[dependencies.librespot-playback]
path = "playback"
[dependencies.librespot-protocol]
path = "protocol"

[build-dependencies]
rand            = "0.7.0"
vergen          = "3.0.4"

[features]
alsa-backend = ["librespot-playback/alsa-backend"]
portaudio-backend = ["librespot-playback/portaudio-backend"]
pulseaudio-backend = ["librespot-playback/pulseaudio-backend"]
jackaudio-backend = ["librespot-playback/jackaudio-backend"]

with-tremor = ["librespot-audio/with-tremor"]
with-vorbis = ["librespot-audio/with-vorbis"]

with-dns-sd = ["librespot-connect/with-dns-sd"]

default = ["librespot-playback/alsa-backend"]
